export const ACTIVITY = {
  QUESTION: "QUESTION#",
  ANSWER: "ANSWER#",
  TOPIC: "TOPIC#",
  QUESTION_UPVOTE: "QUESTIONUPVOTE#",
  ANSWER_UPVOTE: "ANSWERUPVOTE#",
};

export const DELETE_CURRENT_FILE = "__delete_current_file__";
