# This workflow will do a clean install of node dependencies, build the source code and run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Test project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      node-version: "14"

    steps:
      - name: Build and Test project on Node.js ${{ node-version }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ node-version }}
      - uses: microsoft/playwright-github-action@v1
      - run: npm install
      - run: npm run build
      - run: npm run test
